package Form;


import Class.DBconnection;
import Class.User;
import Class.Vehicle;
import Form.frm_Main;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class frm_Main extends javax.swing.JFrame {

    /**
     * Creates new form New_Main
     */
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public String InID;
    int timerun = 0;
    
    String ul;
    String un;
    
    //Save Button
    User ur;
    public String finalid;

    JDesktopPane desktop;
     public int  frm_user ;
frm_Maintenance maintenance;
    public frm_Main() {
        initComponents();
        user();
           new Thread(){
                public void run(){
                    while (timerun == 0){
                    Calendar  cal = new GregorianCalendar();
        
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int AM_PM = cal.get(Calendar.AM_PM);
        
                    int Month = cal.get(Calendar.MONTH);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int year = cal.get(Calendar.YEAR);
        
                    
                    
                    String day_night = "";
                    if (AM_PM == 1){
                        day_night = "PM";
                    }else{
                        day_night = "AM";
                    }
                    
                    String Date = Month+"/ "+day+"/ "+year;
                    String Time = hour+":"+min+":"+sec+" "+day_night;
                    
                    lbl_Date.setText(Date);
                    lbl_Time.setText(Time);
                    }
                }
            }.start();
    }

    private void user(){
         try{
             
           ses_id () ; 
           conn = DBconnection.jdbcConnect();
           String ses = "Select * from tbl_session where ses_id = ?";
           pst = conn.prepareStatement(ses);
           pst.setString(1,InID);
           rs=pst.executeQuery();
           
          if(rs.next()) {
             ul = rs.getString("ses_userlevel");
             un = rs.getString("ses_name");
             lbl_User1.setText(ul+", "+un);
          }
           
       }catch(SQLException | HeadlessException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }
  
  private void center(JInternalFrame internal){
  int x = (jDesktopPane1.getWidth() - internal.getWidth())/2;
  int y = (jDesktopPane1.getHeight() - internal.getHeight())/2;
  
  internal.setLocation(x, y);
 jDesktopPane1.add(internal);
 internal.show();
  }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User1 = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        Reports = new javax.swing.JLabel();
        lbl_Reports = new javax.swing.JLabel();
        lbl_Setting = new javax.swing.JLabel();
        Setting = new javax.swing.JLabel();
        Transaction = new javax.swing.JLabel();
        lbl_Transaction = new javax.swing.JLabel();
        Maintenance = new javax.swing.JLabel();
        lbl_Maintenance = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        lbl_User1 = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPaneBackground = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/User_64.png"))); // NOI18N
        User1.setText(" ");
        User1.setToolTipText("");
        User1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        User1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                User1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                User1MouseExited(evt);
            }
        });
        getContentPane().add(User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 90, 90));

        lbl_User.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_User.setForeground(new java.awt.Color(0, 153, 255));
        lbl_User.setText("Users");
        getContentPane().add(lbl_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 100, -1, -1));

        Reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/Reports_64.png"))); // NOI18N
        Reports.setText(" ");
        Reports.setToolTipText("");
        Reports.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportsMouseExited(evt);
            }
        });
        getContentPane().add(Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 90, 90));

        lbl_Reports.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Reports.setForeground(new java.awt.Color(0, 153, 255));
        lbl_Reports.setText("Reports");
        getContentPane().add(lbl_Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, -1, -1));

        lbl_Setting.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Setting.setForeground(new java.awt.Color(0, 153, 255));
        lbl_Setting.setText("Setting");
        getContentPane().add(lbl_Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, -1, -1));

        Setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/Setting_64.png"))); // NOI18N
        Setting.setText(" ");
        Setting.setToolTipText("");
        Setting.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingMouseExited(evt);
            }
        });
        getContentPane().add(Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 100, 90));

        Transaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Transaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/Transaction_64.png"))); // NOI18N
        Transaction.setText(" ");
        Transaction.setToolTipText("");
        Transaction.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransactionMouseExited(evt);
            }
        });
        getContentPane().add(Transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 30, 110, 90));

        lbl_Transaction.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Transaction.setForeground(new java.awt.Color(0, 153, 255));
        lbl_Transaction.setText("Transactions");
        lbl_Transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_TransactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_TransactionMouseExited(evt);
            }
        });
        getContentPane().add(lbl_Transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        Maintenance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/Maintenance_64.png"))); // NOI18N
        Maintenance.setText(" ");
        Maintenance.setToolTipText("");
        Maintenance.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Maintenance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaintenanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaintenanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaintenanceMouseExited(evt);
            }
        });
        getContentPane().add(Maintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 30, 110, 90));

        lbl_Maintenance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Maintenance.setForeground(new java.awt.Color(0, 153, 255));
        lbl_Maintenance.setText("Maintenances");
        lbl_Maintenance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_MaintenanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_MaintenanceMouseExited(evt);
            }
        });
        getContentPane().add(lbl_Maintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        Exit.setText("  ");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 44, 20));

        Logout.setText("  ");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1189, 695, 174, 40));

        lbl_User1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbl_User1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_User1.setText("   ");
        getContentPane().add(lbl_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 290, 30));

        lbl_Date.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date.setText("   ");
        getContentPane().add(lbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 210, 30));

        lbl_Time.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbl_Time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Time.setText("   ");
        getContentPane().add(lbl_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 700, 210, 30));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane1.setToolTipText("");
        jDesktopPane1.setFocusTraversalPolicyProvider(true);

        jDesktopPaneBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/MainBackground.png"))); // NOI18N
        jDesktopPaneBackground.setText("  ");
        jDesktopPaneBackground.setPreferredSize(new java.awt.Dimension(1340, 570));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jDesktopPaneBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jDesktopPaneBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 124, 1350, 570));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/Main.png"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
       int p = JOptionPane.showConfirmDialog(this,"Are you sure you want to Logout your account ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
             
                ses_id () ; 
                conn = DBconnection.jdbcConnect();
                String ses = "delete  from tbl_session where ses_id = ?";
                pst = conn.prepareStatement(ses);
                pst.setString(1,InID);
                pst.execute();
           
                        if(rs.next()) {
                            
                            
                    }
                        
                        new frm_Login().setVisible(true);
                        this.setVisible(false);
           
            }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
           
        int p = JOptionPane.showConfirmDialog(this,"Are you sure you want to Logout your account ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
             
                ses_id () ; 
                conn = DBconnection.jdbcConnect();
                String ses = "delete  from tbl_session where ses_id = ?";
                pst = conn.prepareStatement(ses);
                pst.setString(1, InID);
                pst.execute();
           
                        if(rs.next()) {
                            
                            
                    }
                        
                        new frm_Login().setVisible(true);
                        this.setVisible(false);
           
            }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_LogoutMouseClicked

    private void MaintenanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintenanceMouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/MaintenanceFocused_64.png"));
        Maintenance.setIcon(II);

    }//GEN-LAST:event_MaintenanceMouseEntered

    private void MaintenanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintenanceMouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/Maintenance_64.png"));
        Maintenance.setIcon(II);

    }//GEN-LAST:event_MaintenanceMouseExited

    private void TransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionMouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/TransactionFocused_64.png"));
        Transaction.setIcon(II);

    }//GEN-LAST:event_TransactionMouseEntered

    private void lbl_MaintenanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MaintenanceMouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/MaintenanceFocused_64.png"));
        Maintenance.setIcon(II);

    }//GEN-LAST:event_lbl_MaintenanceMouseEntered

    private void lbl_MaintenanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MaintenanceMouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/Maintenance_64.png"));
        Maintenance.setIcon(II);
    }//GEN-LAST:event_lbl_MaintenanceMouseExited

    private void TransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionMouseExited
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/Transaction_64.png"));
        Transaction.setIcon(II);
    }//GEN-LAST:event_TransactionMouseExited

    private void lbl_TransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TransactionMouseEntered
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/TransactionFocused_64.png"));
        Transaction.setIcon(II);
    }//GEN-LAST:event_lbl_TransactionMouseEntered

    private void lbl_TransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TransactionMouseExited
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/Transaction_64.png"));
        Transaction.setIcon(II);
    }//GEN-LAST:event_lbl_TransactionMouseExited

    private void SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseEntered
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/SettingFocused_64.png"));
        Setting.setIcon(II);
    }//GEN-LAST:event_SettingMouseEntered

    private void SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseExited
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/Setting_64.png"));
        Setting.setIcon(II);
    }//GEN-LAST:event_SettingMouseExited

    private void ReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseEntered
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/ReportFocused_64.png"));
        Reports.setIcon(II);
    }//GEN-LAST:event_ReportsMouseEntered

    private void ReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseExited
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/Reports_64.png"));
        Reports.setIcon(II);
    }//GEN-LAST:event_ReportsMouseExited

    private void User1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User1MouseEntered
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/UserFocused_64.png"));
        User1.setIcon(II);
    }//GEN-LAST:event_User1MouseEntered

    private void User1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User1MouseExited
         ImageIcon II = new ImageIcon(this.getClass().getResource("/Image/Main/User_64.png"));
        User1.setIcon(II);
    }//GEN-LAST:event_User1MouseExited

    private void User1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User1MouseClicked

        frm_user =0;
        
        if(frm_user ==0){
        frm_User user = new frm_User();      
       center(user);
        
        frm_user = 1;
        }else if (frm_user == 1){
            
        }

    }//GEN-LAST:event_User1MouseClicked

    private void MaintenanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintenanceMouseClicked
        if(!(maintenance instanceof JInternalFrame)){
         maintenance = new frm_Maintenance(jDesktopPane1 , this);
        }
        center(maintenance);
        
    }//GEN-LAST:event_MaintenanceMouseClicked

    private void ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseClicked
   try{
       frm_User user = new frm_User();
       jDesktopPaneBackground.add(user);
       user.setVisible(true);
       
   }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
   }
    }//GEN-LAST:event_ReportsMouseClicked

public void ses_id () {

     String sql = "Select ses_id  from tbl_session";
        try {
                conn = DBconnection.jdbcConnect();
                Statement st = conn.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    InID = (rs.getString(1));
                 }
        } catch (SQLException | NumberFormatException  e) {
            JOptionPane.showMessageDialog(null, e);

        }
  
}        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Maintenance;
    private javax.swing.JLabel Reports;
    private javax.swing.JLabel Setting;
    private javax.swing.JLabel Transaction;
    private javax.swing.JLabel User1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jDesktopPaneBackground;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Maintenance;
    private javax.swing.JLabel lbl_Reports;
    private javax.swing.JLabel lbl_Setting;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_Transaction;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JLabel lbl_User1;
    // End of variables declaration//GEN-END:variables

}
