/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

/**
 *
 * @author Mr Krab
 */


import Class.DBconnection;
import Class.Login;
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
public class frm_Login extends javax.swing.JFrame {

  //Variables
  int xMouse;
  int yMouse;
  Login l;

  Connection conn = null;
  ResultSet rs = null;
  PreparedStatement pst = null;
  
  String username;
  String password;
 
       
    public frm_Login()
    {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotPassword = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        Exit = new javax.swing.JLabel();
        btn_Login = new javax.swing.JLabel();
        Drag = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ForgotPassword.setText("Forgot Password ?");
        ForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgotPasswordMouseExited(evt);
            }
        });
        getContentPane().add(ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        txt_username.setBackground(new java.awt.Color(240, 240, 240));
        txt_username.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(null);
        txt_username.setOpaque(false);
        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 169, 212, 28));

        txt_password.setBackground(new java.awt.Color(240, 240, 240));
        txt_password.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(null);
        txt_password.setOpaque(false);
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 210, 30));

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 30, 30));

        btn_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_LoginMouseDragged(evt);
            }
        });
        btn_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LoginMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 248, 290, 45));

        Drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragMouseDragged(evt);
            }
        });
        Drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DragMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragMousePressed(evt);
            }
        });
        getContentPane().add(Drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login/Login.png"))); // NOI18N
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackgroundMousePressed(evt);
            }
        });
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void BackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BackgroundMouseClicked

    //LoginClickEvent
    private void btn_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseClicked
         username = txt_username.getText();
         password = txt_password.getText();
       

            if(!(txt_username.getText().equals("")) && !(txt_password.getText().equals(""))){
                LoginFunction(username,password);
  
            }else if (!(txt_username.getText().equals("")) && (txt_password.getText().equals(""))){
                 LoginFunction(username, password);   
            }

       
    }//GEN-LAST:event_btn_LoginMouseClicked

    
    private void LoginFunction(String u, String p){
        
        conn = DBconnection.jdbcConnect();


        try{
            String Log = "Select * from tbl_employee where username = ? and password = ?"; 
            pst=conn.prepareStatement(Log);
            pst.setString(1,u);
            pst.setString(2,p);
            

            rs=pst.executeQuery();

            if(rs.next()){
                
                //Input the data of the user to the current session table
                String id = rs.getString("emp_id");
                String fname = rs.getString("emp_fname");
                String ul = rs.getString("user_level");
                
                String session = "Insert into tbl_session (ses_id, ses_name, ses_userlevel) values (?, ?, ?)";
                pst = conn.prepareStatement(session);
                pst.setString(1, id);
                pst.setString(2,fname);
                pst.setString(3, ul);
                
                
                pst.execute();
                
                this.setVisible(false);
                new frm_Main().setVisible(true);

                
            }
            else{
                JOptionPane.showMessageDialog(null,"Account not found try again");

            }
            
      
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void btn_LoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseDragged

    }//GEN-LAST:event_btn_LoginMouseDragged

    private void BackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMousePressed

    }//GEN-LAST:event_BackgroundMousePressed

    private void DragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragMouseDragged
      int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      
      this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_DragMouseDragged

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
      System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void DragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragMousePressed
           xMouse = evt.getX();
           yMouse = evt.getY();
    }//GEN-LAST:event_DragMousePressed

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked

    }//GEN-LAST:event_txt_usernameMouseClicked

    private void DragMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragMouseClicked

       
    }//GEN-LAST:event_DragMouseClicked

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        
    }//GEN-LAST:event_txt_passwordMouseClicked

    private void ForgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPasswordMouseEntered
        ForgotPassword.setText("<html><font color=blue>Forgot Password?</font></html>");
    }//GEN-LAST:event_ForgotPasswordMouseEntered

    private void ForgotPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPasswordMouseExited
        ForgotPassword.setText("<html><font color=black>Forgot Password?</font></html>");
    }//GEN-LAST:event_ForgotPasswordMouseExited

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                   username = txt_username.getText();
         password = txt_password.getText();
       

            if(!(txt_username.getText().equals("")) && !(txt_password.getText().equals(""))){
                LoginFunction(username,password);
  
            }else if (!(txt_username.getText().equals("")) && (txt_password.getText().equals(""))){
                 LoginFunction(username, password);   
            }
            
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
               if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                    username = txt_username.getText();
         password = txt_password.getText();
       

            if(!(txt_username.getText().equals("")) && !(txt_password.getText().equals(""))){
                LoginFunction(username,password);
  
            }else if (!(txt_username.getText().equals("")) && (txt_password.getText().equals(""))){
                 LoginFunction(username, password);   
            }
            
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Drag;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JLabel btn_Login;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
