/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Class.CenterDesktopPane;
import Class.DBconnection;
import Class.User;
import Class.Vehicle;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;


public  class frm_Maintenance extends javax.swing.JInternalFrame {


    Connection conn=null;
    ResultSet rs =null;
    PreparedStatement pst=null;
    
    public String id;
    public String plateno;
    public String model;
    public String type;
    public int capacity;
    public Timer t;
    
    String finalid;
    String vid;
    JDesktopPane desktop;
    JDialog dialog;

    Vehicle v;
    int SaveOrUpdate;
    int SaveOrUpdate2;
    int SaveOrUpdate3;
    JFrame frame;
    
    public frm_Maintenance( JDesktopPane desktop , JFrame frame) {
        initComponents();
        this.desktop= desktop;
        this.frame = frame;

        t = new javax.swing.Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e){
                UpdateTableVehicle();
                UpdateTableEmployee();
                UpdateTableService();
                UpdateTableRentalRate();
        }
        });t.start();
        auto_vid();
         lbl_vid.setText(vid);  
        FillcomboPosition();
        btn_Add.setEnabled(true);
        btn_Delete.setEnabled(false);
        btn_Edit.setEnabled(false);
        //User
        txt_id.setEnabled(false);
        txt_fname.setEnabled(false);
        txt_lname.setEnabled(false);
        txt_mi.setEnabled(false);
        txt_username.setEnabled(false);
        cbo_userlevel.setEnabled(false);
        
        btn_Save1.setEnabled(false);
        btn_Cancel1.setEnabled(false);
        btn_Add1.setEnabled(true);
        btn_Delete1.setEnabled(false);
        btn_Edit1.setEnabled(false);
        
        txt_service.setEnabled(false);
        btn_Save2.setEnabled(false);
        btn_Cancel2.setEnabled(false);
        btn_Add2.setEnabled(true);
        btn_Delete2.setEnabled(false);
        btn_Edit2.setEnabled(false);
        lbl_svcid.setEnabled(false);
        //Rate
        btn_Save4.setEnabled(false);
        btn_Cancel5.setEnabled(false);
        btn_Edit3.setEnabled(false);
        btn_Add3.setEnabled(true);
        btn_Delete3.setEnabled(false);
        txt_RentID.setEnabled(false);
        txt_VehicleType.setEnabled(false);
        txt_Daily.setEnabled(false);
        txt_Weekly.setEnabled(false);
        txt_Monthly.setEnabled(false);
        
        

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        add = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        AddVehicle = new javax.swing.JDialog();
        txt_PlateNo = new javax.swing.JTextField();
        txt_Model = new javax.swing.JTextField();
        txt_Type = new javax.swing.JTextField();
        lbl_vid = new javax.swing.JLabel();
        btn_Save3 = new javax.swing.JButton();
        btn_Upload = new javax.swing.JButton();
        btn_Cancel3 = new javax.swing.JButton();
        spin_Capacity = new javax.swing.JSpinner();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        Background2 = new javax.swing.JLabel();
        EditVehicle = new javax.swing.JDialog();
        txt_PlateNo1 = new javax.swing.JTextField();
        txt_Model1 = new javax.swing.JTextField();
        txt_Type1 = new javax.swing.JTextField();
        btn_Update = new javax.swing.JButton();
        lbl_vid1 = new javax.swing.JLabel();
        btn_Upload1 = new javax.swing.JButton();
        btn_Cancel4 = new javax.swing.JButton();
        spin_Capacity1 = new javax.swing.JSpinner();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        Background1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_vehicle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Vehicle = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Vehicle_Background = new javax.swing.JLabel();
        jPanel_userlevel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_employee = new javax.swing.JTable();
        btn_Save1 = new javax.swing.JButton();
        btn_Cancel1 = new javax.swing.JButton();
        btn_Delete1 = new javax.swing.JButton();
        btn_Add1 = new javax.swing.JButton();
        cbo_userlevel = new javax.swing.JComboBox();
        txt_id = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_mi = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_search1 = new javax.swing.JTextField();
        btn_Edit1 = new javax.swing.JButton();
        Userlevel_Background = new javax.swing.JLabel();
        jPanel_Service = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Service = new javax.swing.JTable();
        btn_Save2 = new javax.swing.JButton();
        btn_Cancel2 = new javax.swing.JButton();
        btn_Edit2 = new javax.swing.JButton();
        btn_Add2 = new javax.swing.JButton();
        btn_Delete2 = new javax.swing.JButton();
        txt_service1 = new javax.swing.JTextField();
        txt_service = new javax.swing.JTextField();
        lbl_svcid = new javax.swing.JLabel();
        Background_Service = new javax.swing.JLabel();
        jPanel_Location = new javax.swing.JPanel();
        Background_Location = new javax.swing.JLabel();
        jPanel_Userlevel = new javax.swing.JPanel();
        jPanel_Rate = new javax.swing.JPanel();
        Background_Rate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_RentalRate = new javax.swing.JTable();
        btn_Save4 = new javax.swing.JButton();
        btn_Cancel5 = new javax.swing.JButton();
        btn_Edit3 = new javax.swing.JButton();
        btn_Add3 = new javax.swing.JButton();
        btn_Delete3 = new javax.swing.JButton();
        txt_RentID = new javax.swing.JTextField();
        txt_VehicleType = new javax.swing.JTextField();
        txt_Daily = new javax.swing.JTextField();
        txt_Weekly = new javax.swing.JTextField();
        txt_Monthly = new javax.swing.JTextField();
        Rental_Background = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPopupMenu1.add(add);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPopupMenu1.add(edit);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(delete);

        AddVehicle.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddVehicle.setTitle("Vehicle");
        AddVehicle.setAlwaysOnTop(true);
        AddVehicle.setMinimumSize(new java.awt.Dimension(900, 460));
        AddVehicle.setResizable(false);
        AddVehicle.setType(java.awt.Window.Type.POPUP);
        AddVehicle.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_PlateNo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_PlateNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_PlateNo.setBorder(null);
        txt_PlateNo.setOpaque(false);
        AddVehicle.getContentPane().add(txt_PlateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 133, 280, 30));

        txt_Model.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_Model.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Model.setBorder(null);
        txt_Model.setOpaque(false);
        AddVehicle.getContentPane().add(txt_Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 200, 280, 30));

        txt_Type.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_Type.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Type.setBorder(null);
        txt_Type.setOpaque(false);
        AddVehicle.getContentPane().add(txt_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 268, 280, 30));

        lbl_vid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_vid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_vid.setText(" ");
        AddVehicle.getContentPane().add(lbl_vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 68, 280, 30));

        btn_Save3.setBackground(new java.awt.Color(35, 31, 32));
        btn_Save3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        btn_Save3.setBorder(null);
        btn_Save3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Save3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Save3MouseExited(evt);
            }
        });
        btn_Save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save3ActionPerformed(evt);
            }
        });
        AddVehicle.getContentPane().add(btn_Save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 173, 53));

        btn_Upload.setBackground(new java.awt.Color(35, 31, 32));
        btn_Upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Upload.png"))); // NOI18N
        btn_Upload.setBorder(null);
        btn_Upload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UploadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UploadMouseExited(evt);
            }
        });
        btn_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UploadActionPerformed(evt);
            }
        });
        AddVehicle.getContentPane().add(btn_Upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 173, 53));

        btn_Cancel3.setBackground(new java.awt.Color(35, 31, 32));
        btn_Cancel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Employee/Cancel.png"))); // NOI18N
        btn_Cancel3.setBorder(null);
        btn_Cancel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cancel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cancel3MouseExited(evt);
            }
        });
        btn_Cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancel3ActionPerformed(evt);
            }
        });
        AddVehicle.getContentPane().add(btn_Cancel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 173, 53));

        spin_Capacity.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        AddVehicle.getContentPane().add(spin_Capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 160, 30));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        AddVehicle.getContentPane().add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 490, 330));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SystemMaintenance/Maintenance_AddVehicle.png"))); // NOI18N
        Background2.setText("   ");
        AddVehicle.getContentPane().add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        EditVehicle.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        EditVehicle.setTitle("Vehicle");
        EditVehicle.setAlwaysOnTop(true);
        EditVehicle.setResizable(false);
        EditVehicle.setType(java.awt.Window.Type.POPUP);
        EditVehicle.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_PlateNo1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_PlateNo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_PlateNo1.setText("   ");
        txt_PlateNo1.setBorder(null);
        txt_PlateNo1.setOpaque(false);
        EditVehicle.getContentPane().add(txt_PlateNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 133, 280, 30));

        txt_Model1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_Model1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Model1.setText("   ");
        txt_Model1.setBorder(null);
        txt_Model1.setOpaque(false);
        EditVehicle.getContentPane().add(txt_Model1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 200, 280, 30));

        txt_Type1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_Type1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Type1.setText("   ");
        txt_Type1.setBorder(null);
        txt_Type1.setOpaque(false);
        EditVehicle.getContentPane().add(txt_Type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 268, 280, 30));

        btn_Update.setBackground(new java.awt.Color(35, 31, 32));
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Update.png"))); // NOI18N
        btn_Update.setBorder(null);
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseExited(evt);
            }
        });
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        EditVehicle.getContentPane().add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 173, 53));

        lbl_vid1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_vid1.setText(" ");
        EditVehicle.getContentPane().add(lbl_vid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 68, 280, 30));

        btn_Upload1.setBackground(new java.awt.Color(35, 31, 32));
        btn_Upload1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Upload.png"))); // NOI18N
        btn_Upload1.setBorder(null);
        btn_Upload1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Upload1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Upload1MouseExited(evt);
            }
        });
        btn_Upload1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Upload1ActionPerformed(evt);
            }
        });
        EditVehicle.getContentPane().add(btn_Upload1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 173, 53));

        btn_Cancel4.setBackground(new java.awt.Color(35, 31, 32));
        btn_Cancel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Employee/Cancel.png"))); // NOI18N
        btn_Cancel4.setBorder(null);
        btn_Cancel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cancel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cancel4MouseExited(evt);
            }
        });
        btn_Cancel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancel4ActionPerformed(evt);
            }
        });
        EditVehicle.getContentPane().add(btn_Cancel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 173, 53));

        spin_Capacity1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        EditVehicle.getContentPane().add(spin_Capacity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 160, 30));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        EditVehicle.getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 490, 330));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SystemMaintenance/Maintenance_AddVehicle.png"))); // NOI18N
        Background1.setText("   ");
        EditVehicle.getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Maintenance");
        setToolTipText("");
        setAutoscrolls(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main/Maintenance_64.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1350, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(35, 31, 33));
        jTabbedPane1.setForeground(new java.awt.Color(35, 31, 33));
        jTabbedPane1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jPanel_vehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_Vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_VehicleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_VehicleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_VehicleMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Vehicle);

        jPanel_vehicle.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 910, 440));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Magnifier_24.png"))); // NOI18N
        jPanel_vehicle.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 50, 30));

        btn_Edit.setBackground(new java.awt.Color(35, 31, 32));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btn_Edit.setBorder(null);
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditMouseExited(evt);
            }
        });
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });
        jPanel_vehicle.add(btn_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 173, 53));

        btn_Delete.setBackground(new java.awt.Color(35, 31, 32));
        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        btn_Delete.setBorder(null);
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseExited(evt);
            }
        });
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel_vehicle.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 173, 53));

        btn_Add.setBackground(new java.awt.Color(35, 31, 32));
        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/AddVehicle.png"))); // NOI18N
        btn_Add.setBorder(null);
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AddMouseExited(evt);
            }
        });
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        jPanel_vehicle.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, 173, 53));

        txt_search.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_search.setBorder(null);
        txt_search.setOpaque(false);
        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchMouseClicked(evt);
            }
        });
        jPanel_vehicle.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 15, 212, 27));
        jPanel_vehicle.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 370, 240));

        Vehicle_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SystemMaintenance/Maintenance_Vehicle.png"))); // NOI18N
        Vehicle_Background.setText("  ");
        Vehicle_Background.setPreferredSize(new java.awt.Dimension(1293, 460));
        jPanel_vehicle.add(Vehicle_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 500));

        jTabbedPane1.addTab(" Vehicles", new javax.swing.ImageIcon(getClass().getResource("/Icon/Vehicle.png")), jPanel_vehicle); // NOI18N

        jPanel_userlevel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_employeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_employee);

        jPanel_userlevel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 760, -1));

        btn_Save1.setBackground(new java.awt.Color(35, 31, 32));
        btn_Save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        btn_Save1.setBorder(null);
        btn_Save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Save1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Save1MouseExited(evt);
            }
        });
        btn_Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save1ActionPerformed(evt);
            }
        });
        jPanel_userlevel.add(btn_Save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 173, 53));

        btn_Cancel1.setBackground(new java.awt.Color(35, 31, 32));
        btn_Cancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel.png"))); // NOI18N
        btn_Cancel1.setBorder(null);
        btn_Cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cancel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cancel1MouseExited(evt);
            }
        });
        btn_Cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancel1ActionPerformed(evt);
            }
        });
        jPanel_userlevel.add(btn_Cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 173, 53));

        btn_Delete1.setBackground(new java.awt.Color(35, 31, 32));
        btn_Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        btn_Delete1.setBorder(null);
        btn_Delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Delete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Delete1MouseExited(evt);
            }
        });
        btn_Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Delete1ActionPerformed(evt);
            }
        });
        jPanel_userlevel.add(btn_Delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 173, 53));

        btn_Add1.setBackground(new java.awt.Color(35, 31, 32));
        btn_Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/AddVehicle.png"))); // NOI18N
        btn_Add1.setBorder(null);
        btn_Add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Add1MouseExited(evt);
            }
        });
        btn_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add1ActionPerformed(evt);
            }
        });
        jPanel_userlevel.add(btn_Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 173, 53));

        cbo_userlevel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_userlevel.add(cbo_userlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 230, 30));

        txt_id.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_id.setText("  ");
        txt_id.setBorder(null);
        txt_id.setOpaque(false);
        jPanel_userlevel.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 74, 220, 25));

        txt_fname.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_fname.setText("  ");
        txt_fname.setBorder(null);
        txt_fname.setOpaque(false);
        jPanel_userlevel.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 143, 220, 26));

        txt_username.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_username.setText("  ");
        txt_username.setBorder(null);
        txt_username.setOpaque(false);
        jPanel_userlevel.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 220, 25));

        txt_mi.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_mi.setText("  ");
        txt_mi.setBorder(null);
        txt_mi.setOpaque(false);
        jPanel_userlevel.add(txt_mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 285, 220, 25));

        txt_lname.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_lname.setText("  ");
        txt_lname.setBorder(null);
        txt_lname.setOpaque(false);
        jPanel_userlevel.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 215, 220, 25));

        txt_search1.setText("  ");
        txt_search1.setBorder(null);
        txt_search1.setOpaque(false);
        txt_search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search1MouseClicked(evt);
            }
        });
        jPanel_userlevel.add(txt_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 22, 220, 25));

        btn_Edit1.setBackground(new java.awt.Color(35, 31, 32));
        btn_Edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btn_Edit1.setBorder(null);
        btn_Edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Edit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Edit1MouseExited(evt);
            }
        });
        btn_Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Edit1ActionPerformed(evt);
            }
        });
        jPanel_userlevel.add(btn_Edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 173, 53));

        Userlevel_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SystemMaintenance/Maintenance_Users.png"))); // NOI18N
        jPanel_userlevel.add(Userlevel_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab(" Employee", new javax.swing.ImageIcon(getClass().getResource("/Icon/Users.png")), jPanel_userlevel); // NOI18N

        jPanel_Service.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_Service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ServiceMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Service);

        jPanel_Service.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 760, -1));

        btn_Save2.setBackground(new java.awt.Color(35, 31, 32));
        btn_Save2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        btn_Save2.setBorder(null);
        btn_Save2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Save2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Save2MouseExited(evt);
            }
        });
        btn_Save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save2ActionPerformed(evt);
            }
        });
        jPanel_Service.add(btn_Save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 173, 53));

        btn_Cancel2.setBackground(new java.awt.Color(35, 31, 32));
        btn_Cancel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel.png"))); // NOI18N
        btn_Cancel2.setBorder(null);
        btn_Cancel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cancel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cancel2MouseExited(evt);
            }
        });
        btn_Cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancel2ActionPerformed(evt);
            }
        });
        jPanel_Service.add(btn_Cancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 173, 53));

        btn_Edit2.setBackground(new java.awt.Color(35, 31, 32));
        btn_Edit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btn_Edit2.setBorder(null);
        btn_Edit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Edit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Edit2MouseExited(evt);
            }
        });
        btn_Edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Edit2ActionPerformed(evt);
            }
        });
        jPanel_Service.add(btn_Edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 173, 53));

        btn_Add2.setBackground(new java.awt.Color(35, 31, 32));
        btn_Add2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/AddVehicle.png"))); // NOI18N
        btn_Add2.setBorder(null);
        btn_Add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Add2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Add2MouseExited(evt);
            }
        });
        btn_Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add2ActionPerformed(evt);
            }
        });
        jPanel_Service.add(btn_Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 173, 53));

        btn_Delete2.setBackground(new java.awt.Color(35, 31, 32));
        btn_Delete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        btn_Delete2.setBorder(null);
        btn_Delete2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Delete2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Delete2MouseExited(evt);
            }
        });
        jPanel_Service.add(btn_Delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 173, 53));

        txt_service1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_service1.setBorder(null);
        txt_service1.setOpaque(false);
        jPanel_Service.add(txt_service1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 213, 26));

        txt_service.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_service.setBorder(null);
        txt_service.setOpaque(false);
        jPanel_Service.add(txt_service, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 142, 220, 25));

        lbl_svcid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel_Service.add(lbl_svcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 73, 220, 27));

        Background_Service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SystemMaintenance/Maintenance_Service.png"))); // NOI18N
        Background_Service.setText("  ");
        jPanel_Service.add(Background_Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        jTabbedPane1.addTab(" Service", new javax.swing.ImageIcon(getClass().getResource("/Icon/Driver.png")), jPanel_Service); // NOI18N

        jPanel_Location.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Location.setText("  ");
        jPanel_Location.add(Background_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Location", new javax.swing.ImageIcon(getClass().getResource("/Icon/Location.png")), jPanel_Location); // NOI18N
        jTabbedPane1.addTab(" User level", new javax.swing.ImageIcon(getClass().getResource("/Icon/bars.png")), jPanel_Userlevel); // NOI18N

        jPanel_Rate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_Rate.add(Background_Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 91, -1, -1));

        jLabel1.setText(" ");
        jPanel_Rate.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 71, -1, -1));

        jTabbedPane6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_RentalRate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_RentalRate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_RentalRateMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_RentalRate);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 57, 740, 390));

        btn_Save4.setBackground(new java.awt.Color(35, 31, 32));
        btn_Save4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        btn_Save4.setBorder(null);
        btn_Save4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Save4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Save4MouseExited(evt);
            }
        });
        btn_Save4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Save4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 173, 53));

        btn_Cancel5.setBackground(new java.awt.Color(35, 31, 32));
        btn_Cancel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel.png"))); // NOI18N
        btn_Cancel5.setBorder(null);
        btn_Cancel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cancel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cancel5MouseExited(evt);
            }
        });
        btn_Cancel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancel5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 173, 53));

        btn_Edit3.setBackground(new java.awt.Color(35, 31, 32));
        btn_Edit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btn_Edit3.setBorder(null);
        btn_Edit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Edit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Edit3MouseExited(evt);
            }
        });
        btn_Edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Edit3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Edit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 173, 53));

        btn_Add3.setBackground(new java.awt.Color(35, 31, 32));
        btn_Add3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/AddVehicle.png"))); // NOI18N
        btn_Add3.setBorder(null);
        btn_Add3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Add3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Add3MouseExited(evt);
            }
        });
        btn_Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 173, 53));

        btn_Delete3.setBackground(new java.awt.Color(35, 31, 32));
        btn_Delete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        btn_Delete3.setBorder(null);
        btn_Delete3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Delete3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Delete3MouseExited(evt);
            }
        });
        jPanel1.add(btn_Delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 173, 53));

        txt_RentID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_RentID.setBorder(null);
        txt_RentID.setOpaque(false);
        jPanel1.add(txt_RentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 65, 210, 27));

        txt_VehicleType.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_VehicleType.setBorder(null);
        txt_VehicleType.setOpaque(false);
        jPanel1.add(txt_VehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 210, 27));

        txt_Daily.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_Daily.setBorder(null);
        txt_Daily.setOpaque(false);
        jPanel1.add(txt_Daily, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 210, 27));

        txt_Weekly.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_Weekly.setBorder(null);
        txt_Weekly.setOpaque(false);
        jPanel1.add(txt_Weekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 254, 210, 27));

        txt_Monthly.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_Monthly.setBorder(null);
        txt_Monthly.setOpaque(false);
        jPanel1.add(txt_Monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 314, 210, 27));

        Rental_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SystemMaintenance/Maintenance_Rate_Rental.png"))); // NOI18N
        Rental_Background.setText(" ");
        jPanel1.add(Rental_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1305, 463));

        jTabbedPane6.addTab("Car Rental", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1305, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Car Hire", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1305, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Chauffeur", jPanel3);

        jPanel_Rate.add(jTabbedPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 500));

        jTabbedPane1.addTab(" Rate", new javax.swing.ImageIcon(getClass().getResource("/Icon/payment.png")), jPanel_Rate); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1320, 540));

        Background.setText("  ");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add1ActionPerformed
        SaveOrUpdate = 1;
        txt_id.setText(auto_id());
        
        txt_fname.setText("");
        txt_fname.setEnabled(true);
        
        txt_lname.setText("");
        txt_lname.setEnabled(true);
        
        txt_mi.setText("");
        txt_mi.setEnabled(true);
        
        txt_username.setText("");
        txt_username.setEnabled(true);
        
        cbo_userlevel.setEnabled(true);
        
        btn_Save1.setEnabled(true);
        btn_Cancel1.setEnabled(true);
        btn_Add1.setEnabled(false);
        btn_Edit1.setEnabled(false);
        btn_Delete1.setEnabled(false);
        
        
        
       
        
    }//GEN-LAST:event_btn_Add1ActionPerformed

    
public String auto_id() {  
     Calendar  cal = new GregorianCalendar();

                    int year = cal.get(Calendar.YEAR);
      
     String sql = "Select MAX(emp_id)  from tbl_Employee";
        try {
                conn = DBconnection.jdbcConnect();
                Statement st = conn.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next()) {
                   String id = rs.getString("MAX(emp_id)");
                   String format = id.substring(9);
                   int id1 = Integer.parseInt(format) + 1;
                   
                   if(id1 <= 9 && id1 >= 1){
                       finalid = "USR"+"-"+String.valueOf(year)+"-"+"000"+id1;
                   }else if(id1 <= 99 && id1 >= 10){
                       finalid = "USR"+"-"+String.valueOf(year)+"-"+"00"+id1;
                   }else if(id1 <= 999 && id1 >= 100){
                       finalid = "USR"+"-"+String.valueOf(year)+"-"+"0"+id1;
                   }else if(id1 <= 9999 && id1 >= 1000){
                       finalid = "USR"+"-"+String.valueOf(year)+"-"+id1;
                   }
                 }
        } catch (Exception e) {
 
            finalid = "USR"+"-"+String.valueOf(year)+"-"+"0001";
        } 
        
  return finalid;      
}

public String auto_svcid() {  
     Calendar  cal = new GregorianCalendar();

                    int year = cal.get(Calendar.YEAR);
      
     String sql = "Select MAX(svc_id)  from tbl_service";
        try {
                conn = DBconnection.jdbcConnect();
                Statement st = conn.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next()) {
                   String id = rs.getString("MAX(svc_id)");
                   String format = id.substring(9);
                   int id1 = Integer.parseInt(format) + 1;
                   
                   if(id1 <= 9 && id1 >= 1){
                       finalid = "SVC"+"-"+String.valueOf(year)+"-"+"000"+id1;
                   }else if(id1 <= 99 && id1 >= 10){
                       finalid = "SVC"+"-"+String.valueOf(year)+"-"+"00"+id1;
                   }else if(id1 <= 999 && id1 >= 100){
                       finalid = "SVC"+"-"+String.valueOf(year)+"-"+"0"+id1;
                   }else if(id1 <= 9999 && id1 >= 1000){
                       finalid = "SVC"+"-"+String.valueOf(year)+"-"+id1;
                   }
                 }
        } catch (Exception e) {
 
            finalid = "SVC"+"-"+String.valueOf(year)+"-"+"0001";
        } 
        
  return finalid;      
}

public String auto_rentid() {  
     Calendar  cal = new GregorianCalendar();

                    int year = cal.get(Calendar.YEAR);
      
     String sql = "Select MAX(rent_id)  from tbl_rentalrate";
        try {
                conn = DBconnection.jdbcConnect();
                Statement st = conn.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next()) {
                   String id = rs.getString("MAX(rent_id)");
                   String format = id.substring(9);
                   int id1 = Integer.parseInt(format) + 1;
                   
                   if(id1 <= 9 && id1 >= 1){
                       finalid = "RTL"+"-"+String.valueOf(year)+"-"+"000"+id1;
                   }else if(id1 <= 99 && id1 >= 10){
                       finalid = "RTL"+"-"+String.valueOf(year)+"-"+"00"+id1;
                   }else if(id1 <= 999 && id1 >= 100){
                       finalid = "RTL"+"-"+String.valueOf(year)+"-"+"0"+id1;
                   }else if(id1 <= 9999 && id1 >= 1000){
                       finalid = "RTL"+"-"+String.valueOf(year)+"-"+id1;
                   }
                 }
        } catch (Exception e) {
 
            finalid = "RTL"+"-"+String.valueOf(year)+"-"+"0001";
        } 
        
  return finalid;      
}




    private void btn_Add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Add1MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicle.png"));

        btn_Add1.setIcon(II);

    }//GEN-LAST:event_btn_Add1MouseExited

    private void btn_Add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Add1MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicleFocused.png"));

        btn_Add1.setIcon(II);
    }//GEN-LAST:event_btn_Add1MouseEntered

    private void btn_Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Delete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Delete1ActionPerformed

    private void btn_Delete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Delete1MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Delete.png"));

        btn_Delete1.setIcon(II);
    }//GEN-LAST:event_btn_Delete1MouseExited

    private void btn_Delete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Delete1MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/DeleteFocused.png"));

        btn_Delete1.setIcon(II);
    }//GEN-LAST:event_btn_Delete1MouseEntered

    private void btn_Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancel1ActionPerformed
 int p = JOptionPane.showConfirmDialog(this,"Are you sure you want to cancel ?","Confirm", JOptionPane.YES_NO_OPTION);
    if(p == 0){
        txt_id.setText("");
        txt_fname.setText("");
        txt_fname.setEnabled(false);
        
        txt_lname.setText("");
        txt_lname.setEnabled(false);
        
        txt_mi.setText("");
        txt_mi.setEnabled(false);
        
        txt_username.setText("");
        txt_username.setEnabled(false);
        
        cbo_userlevel.setEnabled(false);
        
        btn_Save1.setEnabled(false);
        btn_Cancel1.setEnabled(false);
        btn_Add1.setEnabled(true);
        btn_Edit1.setEnabled(false);
        btn_Delete1.setEnabled(false);
    }
    }//GEN-LAST:event_btn_Cancel1ActionPerformed

    private void btn_Cancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel1MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Cancel.png"));

        btn_Cancel1.setIcon(II);
    }//GEN-LAST:event_btn_Cancel1MouseExited

    private void btn_Cancel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel1MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/CancelFocused.png"));

        btn_Cancel1.setIcon(II);
    }//GEN-LAST:event_btn_Cancel1MouseEntered

    private void btn_Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save1ActionPerformed
            //Save
           
            
           String fname = txt_fname.getText();
           String lname = txt_lname.getText();
           String mi = txt_mi.getText();
           String username = txt_username.getText();
           String userlevel = cbo_userlevel.getSelectedItem().toString();
           String id = txt_id.getText();
            User usr = new User();          
           
            
            
                try{
                    
                    //Save
                    if(SaveOrUpdate == 1){

                    usr.SaveToEmployee(fname, lname, mi, username, userlevel, id);
                    
                   //Update    
                    }else if(SaveOrUpdate == 0){
                    
                   usr.UpdateToEmployee(fname, lname, mi, username, userlevel, id);
                   }
                    
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);                    
                }
                
        btn_Add.setEnabled(true);
        btn_Delete.setEnabled(false);
        btn_Edit.setEnabled(false);
        
        txt_id.setText("");
        
        txt_fname.setText("");
        txt_fname.setEnabled(false);
        
        txt_lname.setText("");
        txt_lname.setEnabled(false);
        
        txt_mi.setText("");
        txt_mi.setEnabled(false);
        
        txt_username.setText("");
        txt_username.setEnabled(false);
        
        cbo_userlevel.setEnabled(false);
        
        btn_Save1.setEnabled(false);
        btn_Cancel1.setEnabled(false);
        btn_Add1.setEnabled(true);
        btn_Delete1.setEnabled(false);
        btn_Edit1.setEnabled(false);                
                t.start();
            

    }//GEN-LAST:event_btn_Save1ActionPerformed

    private void btn_Save1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save1MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Save.png"));

         btn_Save1.setIcon(II);
    }//GEN-LAST:event_btn_Save1MouseExited

    private void btn_Save1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save1MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/SaveFocused.png"));

        btn_Save1.setIcon(II);
    }//GEN-LAST:event_btn_Save1MouseEntered

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
//     CenterDesktopPane c = new CenterDesktopPane();
//        if(!(b instanceof JInternalFrame)){
//     b = new frm_AddVehicle();
//      }
//    DesktopPane(desktop,AddVehicle); 
    frame.setEnabled(false);
    AddVehicle.setLocationRelativeTo(null);
    AddVehicle.show();
    }//GEN-LAST:event_btn_AddActionPerformed

public void DesktopPane(JDesktopPane jDesktopPane1, JDialog internal){
        
   int x = (jDesktopPane1.getWidth() - internal.getWidth())/2;
  int y = (jDesktopPane1.getHeight() - internal.getHeight())/2;
  
  if(internal.isShowing()){
        internal.setLocation(x, y);
  }
  else
  {
        internal.setLocation(x, y);
       jDesktopPane1.add(internal);
       internal.show();
  }
    }    
    
    private void btn_AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicle.png"));

        btn_Add.setIcon(II);
    }//GEN-LAST:event_btn_AddMouseExited

    private void btn_AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicleFocused.png"));

        btn_Add.setIcon(II);
    }//GEN-LAST:event_btn_AddMouseEntered

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed

        int p = JOptionPane.showConfirmDialog(this,"Are you sure you want to Delete this vehicle? ","Confirm",JOptionPane.YES_NO_OPTION);

        if(p==0){
            try{
                conn = DBconnection.jdbcConnect();
                int row = tbl_Vehicle.getRowCount();
                String table_click = (tbl_Vehicle.getModel().getValueAt(row, 0).toString());
                String sql  = "Delete * from tbl_Vehicle where plateno = '"+table_click+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(this, "Deleted");
                UpdateTableVehicle();

            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_btn_DeleteActionPerformed

    
    private void btn_DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Delete.png"));

        btn_Delete.setIcon(II);
    }//GEN-LAST:event_btn_DeleteMouseExited

    private void btn_DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/DeleteFocused.png"));

        btn_Delete.setIcon(II);
    }//GEN-LAST:event_btn_DeleteMouseEntered

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        t.start();
        frame.setEnabled(false);
   
    EditVehicle.setLocationRelativeTo(null);
    EditVehicle.setSize(900, 460);
    EditVehicle.show();
   
   
        lbl_vid1.setText(id);
        txt_PlateNo1.setText(plateno);
        txt_Model1.setText(model);
        txt_Type1.setText(type);
        spin_Capacity1.setValue(capacity);
   
    
    btn_Edit.setEnabled(false);
    btn_Add.setEnabled(true);
    btn_Delete.setEnabled(false);
    
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Edit.png"));

        btn_Edit.setIcon(II);
    }//GEN-LAST:event_btn_EditMouseExited

    private void btn_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseEntered

        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/EditFocused.png"));

        btn_Edit.setIcon(II);
    }//GEN-LAST:event_btn_EditMouseEntered

    private void tbl_VehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_VehicleMouseClicked

        
        btn_Edit.setEnabled(true);
        btn_Add.setEnabled(true);
        btn_Delete.setEnabled(true);

        t.stop();
          int row = tbl_Vehicle.getSelectedRow();
            String table_click = tbl_Vehicle.getModel().getValueAt(row,0).toString();
        try{
          
            String sql = "Select *  from tbl_vehicle where v_id = '"+table_click+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){
                
                id = rs.getString("v_id");
                plateno = rs.getString("plateno");
                model = rs.getString("model");
                type = rs.getString("type");
                capacity = rs.getInt("capacity");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbl_VehicleMouseClicked

    private void tbl_VehicleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_VehicleMousePressed
if (SwingUtilities.isRightMouseButton(evt)){
            
            // get the coordinates of the mouse click
            Point p = evt.getPoint();
            
            // get the row index  that contains  that coordinate
            int rowNumber = tbl_Vehicle.rowAtPoint(p);
            
            // get the ListSelectionModel of the JTable
            ListSelectionModel model   =     tbl_Vehicle.getSelectionModel();
            
            // set the selected interval of rows . using  the rowNumber
            // variable for the beginning and end  selects only that one row
            model.setSelectionInterval(rowNumber, rowNumber);

            
            jPopupMenu1.show(tbl_Vehicle, evt.getX(), evt.getY());
        }  

            
            
    }//GEN-LAST:event_tbl_VehicleMousePressed

    private void tbl_VehicleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_VehicleMouseReleased
   
    }//GEN-LAST:event_tbl_VehicleMouseReleased

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
            t.start();
    }//GEN-LAST:event_deleteActionPerformed

    //Get the Value of the table user from tbl_userlevel
     private void FillcomboPosition(){
         try{
            conn = DBconnection.jdbcConnect();
            String sql = "Select user_level from tbl_userlevel";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                cbo_userlevel.addItem(rs.getString("user_level"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }    
    
    
    private void tbl_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_employeeMouseClicked
  try{
            conn = DBconnection.jdbcConnect();
            t.stop();
            int row = tbl_employee.getSelectedRow();
            String Table_Click =(tbl_employee.getModel().getValueAt(row,0).toString());
            String sql = "Select * from tbl_employee where emp_id = '"+Table_Click+"'";
            pst = conn.prepareStatement(sql);
            rs =pst.executeQuery();

            if(rs.next()){

                String id = rs.getString("emp_id");
                txt_id.setText(id);
                
                String fname = rs.getString("emp_fname");
                txt_fname.setText(fname);

                String lname = rs.getString("emp_lname");
                txt_lname.setText(lname);

                String mi = rs.getString("emp_mi");
                txt_mi.setText(mi);

                String username = rs.getString("username");
                 txt_username.setText(username);
                
                String userlevel = rs.getString("user_level");
                cbo_userlevel.setSelectedItem(userlevel);

                   txt_id.enable(false);
                   txt_fname.enable(false);
                   txt_lname.enable(false);
                   txt_mi.enable(false);
                   txt_username.enable(false);
                   cbo_userlevel.setEnabled(false);
                   
                btn_Delete1.setEnabled(true);
                btn_Add1.setEnabled(true);
                btn_Edit1.setEnabled(true);
                btn_Save1.setEnabled(false);
                btn_Cancel1.setEnabled(false);
                
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_tbl_employeeMouseClicked

    private void btn_Edit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Edit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Edit1MouseEntered

    private void btn_Edit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Edit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Edit1MouseExited

    private void btn_Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Edit1ActionPerformed

SaveOrUpdate = 0;        
txt_fname.setEnabled(true);
txt_lname.setEnabled(true);
txt_mi.setEnabled(true);
txt_username.setEnabled(true);
cbo_userlevel.setEnabled(true);

btn_Save1.setEnabled(true);
btn_Cancel1.setEnabled(true);
btn_Add1.setEnabled(false);
btn_Edit1.setEnabled(false);
btn_Delete1.setEnabled(false);
    }//GEN-LAST:event_btn_Edit1ActionPerformed

    private void txt_search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search1MouseClicked
        t.start();
        btn_Save1.setEnabled(false);
        btn_Add1.setEnabled(true);
        btn_Edit1.setEnabled(false);
        btn_Delete1.setEnabled(false);
        btn_Cancel1.setEnabled(false);
        
        txt_id.setText("");
        txt_fname.setText("");
        txt_lname.setText("");
        txt_mi.setText("");
        txt_username.setText("");
    }//GEN-LAST:event_txt_search1MouseClicked

    private void txt_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseClicked
        t.start();
        btn_Add.setEnabled(true);
        btn_Edit.setEnabled(false);
        btn_Delete.setEnabled(false);
    }//GEN-LAST:event_txt_searchMouseClicked

    private void btn_Save3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save3MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/SaveFocused.png"));
        btn_Save3.setIcon(II);
    }//GEN-LAST:event_btn_Save3MouseEntered

    private void btn_Save3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save3MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Save.png"));
        btn_Save3.setIcon(II);
    }//GEN-LAST:event_btn_Save3MouseExited

 public  String auto_vid(){
        Calendar  cal = new GregorianCalendar();

                    int year = cal.get(Calendar.YEAR);
      
     String sql = "Select MAX(v_id)  from tbl_Vehicle";
        try {
                conn = DBconnection.jdbcConnect();
                Statement st = conn.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next()) {
                   String id = rs.getString("MAX(v_id)");
                   String format = id.substring(9);
                   int id1 = Integer.parseInt(format) + 1;
                   
                   if(id1 <= 9 && id1 >= 1){
                       vid = "VHC"+"-"+String.valueOf(year)+"-"+"000"+id1;
                   }else if(id1 <= 99 && id1 >= 10){
                       vid = "VHC"+"-"+String.valueOf(year)+"-"+"00"+id1;
                   }else if(id1 <= 999 && id1 >= 100){
                       vid = "VHC"+"-"+String.valueOf(year)+"-"+"0"+id1;
                   }else if(id1 <= 9999 && id1 >= 1000){
                       vid = "VHC"+"-"+String.valueOf(year)+"-"+id1;
                   }
                 }
        } catch (Exception e) {
 
            vid = "VHC"+"-"+String.valueOf(year)+"-"+"0001";
        }
return vid;
 }   
    
    private void btn_Save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save3ActionPerformed

  
        
        
        
        String plateno = txt_PlateNo.getText();
        String model = txt_Model.getText();
        String type = txt_Type.getText();
        spin_Capacity.getValue();
        int capacity = (Integer)spin_Capacity.getValue();


        if((txt_PlateNo.getText().equals("") || (txt_Model.getText().equals("")) || (txt_Type.getText().equals("")))){
            JOptionPane.showMessageDialog(null,"Please complete the field");
        }else{
            Vehicle vehicle = new Vehicle();
            vehicle.SaveToVehicle(vid,plateno, model, type, capacity);
            AddVehicle.hide();
            
            lbl_vid.setText("");
            txt_PlateNo.setText("");
            txt_Model.setText("");
            txt_Type.setText("");     
            spin_Capacity.setValue(0);
            
            frame.setEnabled(true);
            
            
        }
    }//GEN-LAST:event_btn_Save3ActionPerformed

    private void btn_UploadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UploadMouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/UploadFocused.png"));
        btn_Upload.setIcon(II);
    }//GEN-LAST:event_btn_UploadMouseEntered

    private void btn_UploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UploadMouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Upload.png"));
        btn_Upload.setIcon(II);
    }//GEN-LAST:event_btn_UploadMouseExited

    private void btn_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UploadActionPerformed

    private void btn_Cancel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel3MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/CancelFocused.png"));
        btn_Cancel3.setIcon(II);
    }//GEN-LAST:event_btn_Cancel3MouseEntered

    private void btn_Cancel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel3MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Cancel.png"));
        btn_Cancel3.setIcon(II);
    }//GEN-LAST:event_btn_Cancel3MouseExited

    private void btn_Cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancel3ActionPerformed
            lbl_vid.setText("");
            txt_PlateNo.setText("");
            txt_Model.setText("");
            txt_Type.setText("");     
            spin_Capacity.setValue(0);       
        AddVehicle.hide();
        frame.setVisible(true);
       
    }//GEN-LAST:event_btn_Cancel3ActionPerformed

    private void btn_Save2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save2MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/SaveFocused.png"));

        btn_Save2.setIcon(II);
    }//GEN-LAST:event_btn_Save2MouseEntered

    private void btn_Save2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save2MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Save.png"));

        btn_Save2.setIcon(II);
    }//GEN-LAST:event_btn_Save2MouseExited

    private void btn_Cancel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel2MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/CancelFocused.png"));

        btn_Cancel2.setIcon(II);
    }//GEN-LAST:event_btn_Cancel2MouseEntered

    private void btn_Cancel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel2MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Cancel.png"));

        btn_Cancel2.setIcon(II);
    }//GEN-LAST:event_btn_Cancel2MouseExited

    private void btn_Edit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Edit2MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/EditFocused.png"));

        btn_Edit2.setIcon(II);
    }//GEN-LAST:event_btn_Edit2MouseEntered

    private void btn_Edit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Edit2MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Edit.png"));

        btn_Edit2.setIcon(II);
    }//GEN-LAST:event_btn_Edit2MouseExited

    private void btn_Add2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Add2MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicleFocused.png"));

        btn_Add2.setIcon(II);
    }//GEN-LAST:event_btn_Add2MouseEntered

    private void btn_Add2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Add2MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicle.png"));

        btn_Add2.setIcon(II);
    }//GEN-LAST:event_btn_Add2MouseExited

    private void btn_Delete2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Delete2MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/DeleteFocused.png"));

        btn_Delete2.setIcon(II);
    }//GEN-LAST:event_btn_Delete2MouseEntered

    private void btn_Delete2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Delete2MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Delete.png"));

        btn_Delete2.setIcon(II);
    }//GEN-LAST:event_btn_Delete2MouseExited

    private void tbl_ServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ServiceMouseClicked
        t.stop();
        
        try{
            conn = DBconnection.jdbcConnect();
            int row = tbl_Service.getSelectedRow();
            String table_click = (tbl_Service.getModel().getValueAt(row, 0).toString());


            String sql = "Select * from tbl_Service where svc_id = '"+table_click+"'";
            pst = conn.prepareStatement(sql);
            rs =pst.executeQuery();
            
            if(rs.next()){
                
                String svcid = rs.getString("svc_id");
                lbl_svcid.setText(svcid);
                
                String service = rs.getString("Service_Type");
                txt_service.setText(service);
                
            }
            
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        btn_Add2.setEnabled(true);
        btn_Edit2.setEnabled(true);
        btn_Delete2.setEnabled(true);
        
        
    }//GEN-LAST:event_tbl_ServiceMouseClicked

    private void btn_UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/UpdateFocused.png"));
        btn_Update.setIcon(II);
    }//GEN-LAST:event_btn_UpdateMouseEntered

    private void btn_UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Update.png"));
        btn_Update.setIcon(II);
    }//GEN-LAST:event_btn_UpdateMouseExited

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        String i = lbl_vid.getText();
        String p = txt_PlateNo.getText();
        String m = txt_Model.getText();
        String t = txt_Type.getText();
        int c = (Integer)spin_Capacity.getValue();

        int r = JOptionPane.showConfirmDialog(this,"Are you sure you want to update ?","Confirm",JOptionPane.YES_NO_OPTION);

        if(r==0){
            v = new Vehicle();
            v.UpdateToVehicle(i, p, m, t, c);
        }

        EditVehicle.hide();
        lbl_vid.setText("");
        txt_PlateNo.setText("");
        txt_Model.setText("");
        txt_Type.setText("");
        spin_Capacity.setValue(0);
        frame.setEnabled(true);
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_Upload1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Upload1MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/UploadFocused.png"));
        btn_Upload.setIcon(II);
    }//GEN-LAST:event_btn_Upload1MouseEntered

    private void btn_Upload1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Upload1MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Upload.png"));
        btn_Upload.setIcon(II);
    }//GEN-LAST:event_btn_Upload1MouseExited

    private void btn_Upload1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Upload1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Upload1ActionPerformed

    private void btn_Cancel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel4MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/CancelFocused.png"));
        btn_Cancel1.setIcon(II);
    }//GEN-LAST:event_btn_Cancel4MouseEntered

    private void btn_Cancel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel4MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Cancel.png"));
        btn_Cancel1.setIcon(II);
    }//GEN-LAST:event_btn_Cancel4MouseExited

    private void btn_Cancel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancel4ActionPerformed
        EditVehicle.hide();
        lbl_vid.setText("");
        txt_PlateNo.setText("");
        txt_Model.setText("");
        txt_Type.setText("");
        spin_Capacity.setValue(0);
        frame.setEnabled(true);
    }//GEN-LAST:event_btn_Cancel4ActionPerformed

    private void btn_Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add2ActionPerformed

        SaveOrUpdate2 = 1;
            lbl_svcid.setText(auto_svcid());
            txt_service.setText("");
            txt_service.setEnabled(true);
            
            btn_Save2.setEnabled(true);
            btn_Cancel2.setEnabled(true);
            btn_Edit2.setEnabled(false);
            btn_Add2.setEnabled(false);
            btn_Delete2.setEnabled(false);
    }//GEN-LAST:event_btn_Add2ActionPerformed

    private void btn_Save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save2ActionPerformed
        
        String svcid = lbl_svcid.getText();
        String serive = txt_service.getText();
        try{
            
            if(SaveOrUpdate2 == 1){
           conn = DBconnection.jdbcConnect();                  
             String sql = "Insert into tbl_Service (svc_id,service_type)values(?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, auto_svcid());
            pst.setString(2, txt_service.getText());
            pst.execute();    
            JOptionPane.showMessageDialog(null, "Saved");
            
            
            
            }else if(SaveOrUpdate2 == 0){
           conn = DBconnection.jdbcConnect();                   
                String update = "Update tbl_Service set service_type = '"+serive+"'  where svc_id =  '" + svcid+"'  ";
                
               pst = conn.prepareStatement(update);
            pst.execute();                    
            JOptionPane.showMessageDialog(null, "Update");            
            }
           
            
            t.start();
           
            
            lbl_svcid.setText("");
            txt_service.setText("");
            txt_service.setEnabled(false);
            
            btn_Save2.setEnabled(false);
            btn_Cancel2.setEnabled(false);
            btn_Edit2.setEnabled(false);
            btn_Add2.setEnabled(true);
            btn_Delete.setEnabled(false);
            
            

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_Save2ActionPerformed

    private void btn_Cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancel2ActionPerformed
            lbl_svcid.setText("");
            txt_service.setText("");
            txt_service.setEnabled(false);
            
            btn_Save2.setEnabled(false);
            btn_Cancel2.setEnabled(false);
            btn_Edit2.setEnabled(false);
            btn_Add2.setEnabled(true);
            btn_Delete2.setEnabled(false);
    }//GEN-LAST:event_btn_Cancel2ActionPerformed

    private void btn_Edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Edit2ActionPerformed
SaveOrUpdate2 = 0;
txt_service.setEnabled(true);


            btn_Save2.setEnabled(true);
            btn_Cancel2.setEnabled(true);
            btn_Edit2.setEnabled(false);
            btn_Add2.setEnabled(false);
            btn_Delete2.setEnabled(false);
    }//GEN-LAST:event_btn_Edit2ActionPerformed

    private void btn_Save4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save4MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/SaveFocused.png"));
        btn_Save4.setIcon(II);
    }//GEN-LAST:event_btn_Save4MouseEntered

    private void btn_Save4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save4MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Save.png"));
        btn_Save4.setIcon(II);
    }//GEN-LAST:event_btn_Save4MouseExited

    private void btn_Cancel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel5MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/CancelFocused.png"));
        btn_Cancel5.setIcon(II);
    }//GEN-LAST:event_btn_Cancel5MouseEntered

    private void btn_Cancel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancel5MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Cancel.png"));
        btn_Cancel5.setIcon(II);
    }//GEN-LAST:event_btn_Cancel5MouseExited

    private void btn_Edit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Edit3MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/EditFocused.png"));
        btn_Edit3.setIcon(II);
    }//GEN-LAST:event_btn_Edit3MouseEntered

    private void btn_Edit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Edit3MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Edit.png"));
        btn_Edit3.setIcon(II);
    }//GEN-LAST:event_btn_Edit3MouseExited

    private void btn_Add3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Add3MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicleFocused.png"));
        btn_Add3.setIcon(II);
    }//GEN-LAST:event_btn_Add3MouseEntered

    private void btn_Add3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Add3MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/AddVehicle.png"));
        btn_Add3.setIcon(II);
    }//GEN-LAST:event_btn_Add3MouseExited

    private void btn_Delete3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Delete3MouseEntered
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/DeleteFocused.png"));
        btn_Delete3.setIcon(II);
    }//GEN-LAST:event_btn_Delete3MouseEntered

    private void btn_Delete3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Delete3MouseExited
        ImageIcon II = new ImageIcon(this.getClass().getResource("/Icon/Delete.png"));
        btn_Delete3.setIcon(II);
    }//GEN-LAST:event_btn_Delete3MouseExited

    private void tbl_RentalRateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_RentalRateMouseClicked
    try{
            conn = DBconnection.jdbcConnect();
            t.stop();
            int row = tbl_RentalRate.getSelectedRow();
            String Table_Click =(tbl_RentalRate.getModel().getValueAt(row,0).toString());
            String sql = "Select * from tbl_RentalRate where Rent_id = '"+Table_Click+"'";
            pst = conn.prepareStatement(sql);
            rs =pst.executeQuery();

            if(rs.next()){

                String id = rs.getString("Rent_ID");
                txt_RentID.setText(id);
                
                String Type = rs.getString("Rental_Type");
                txt_VehicleType.setText(Type);

                String Daily = rs.getString("Rental_Daily");
                txt_Daily.setText(Daily);

                String Weekly = rs.getString("Rental_Weekly");
                txt_Weekly.setText(Weekly);

                String Monthly = rs.getString("Rental_Monthly");
                 txt_Monthly.setText(Monthly);

                btn_Delete3.setEnabled(true);
                btn_Add3.setEnabled(true);
                btn_Edit3.setEnabled(true);
                btn_Save4.setEnabled(false);
                btn_Cancel5.setEnabled(false);
                
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_tbl_RentalRateMouseClicked

    private void btn_Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add3ActionPerformed
        SaveOrUpdate3 = 1;
        txt_VehicleType.setEnabled(true);
        txt_Daily.setEnabled(true);
        txt_Weekly.setEnabled(true);
        txt_Monthly.setEnabled(true);
        
        txt_RentID.setText("");
        txt_VehicleType.setText("");
        txt_Daily.setText("");
        txt_Weekly.setText("");
        txt_Monthly.setText("");        
        
        btn_Save4.setEnabled(true);
        btn_Cancel5.setEnabled(true);
        btn_Edit3.setEnabled(false);
        btn_Add3.setEnabled(false);
        btn_Delete3.setEnabled(false);
        
        
    }//GEN-LAST:event_btn_Add3ActionPerformed

    private void btn_Save4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save4ActionPerformed
        String vType = txt_VehicleType.getText();
        String Daily = txt_Daily.getText();
        String Weekly = txt_Weekly.getText();
        String Monthly = txt_Monthly.getText();
        
        if(SaveOrUpdate3 == 1){ //Save
            try{
                conn = DBconnection.jdbcConnect();
                String insert = "Insert into tbl_RentalRate (Rent_id, Rental_Type, Rental_Daily, Rental_Weekly, Rental_Monthly)values(?, ?, ?, ?, ?)";
                pst = conn.prepareStatement(insert);
                pst.setString(1, auto_rentid());
                pst.setString(2, txt_VehicleType.getText());
                pst.setString(3, txt_Daily.getText());
                pst.setString(4, txt_Weekly.getText());
                pst.setString(5, txt_Monthly.getText());
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Saved");
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else if (SaveOrUpdate3 == 0){ //Update
            try{
                conn = DBconnection.jdbcConnect();
                
                String update = "Update tbl_rentalrate set Rent_id = ' "+auto_rentid()+" ', Reint_Type = ' "+vType+" ', Rental_Daily =   ' "+Daily+" ', Rental_Weekly = ' "+Weekly+" ', Rental_Monthly = ' "+Monthly+" '  ";
                pst = conn.prepareStatement(update);
                pst.execute();
                
                JOptionPane.showMessageDialog(null,"Update");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            
           txt_RentID.setText("");
           txt_VehicleType.setText("");
           txt_Daily.setText("");
           txt_Weekly.setText("");
           txt_Monthly.setText("");
           
           btn_Save4.setEnabled(false);
           btn_Cancel5.setEnabled(false);
           btn_Edit3.setEnabled(false);
           btn_Add3.setEnabled(true);
           btn_Delete3.setEnabled(false);
           
            
            
        }
    }//GEN-LAST:event_btn_Save4ActionPerformed

    private void btn_Edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Edit3ActionPerformed
      SaveOrUpdate3 = 0;
      txt_VehicleType.setEnabled(true);
      txt_Daily.setEnabled(true);
      txt_Weekly.setEnabled(true);
      txt_Monthly.setEnabled(true);
      
      btn_Save4.setEnabled(true);
      btn_Cancel5.setEnabled(true);
      btn_Edit3.setEnabled(false);
      btn_Add.setEnabled(false);
      btn_Delete.setEnabled(false);

    }//GEN-LAST:event_btn_Edit3ActionPerformed

    private void btn_Cancel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancel5ActionPerformed
           txt_VehicleType.setText("");
           txt_Daily.setText("");
           txt_Weekly.setText("");
           txt_Monthly.setText("");
           
           btn_Save4.setEnabled(false);
           btn_Cancel5.setEnabled(false);
           btn_Edit3.setEnabled(false);
           btn_Add3.setEnabled(true);
           btn_Delete3.setEnabled(false);
    }//GEN-LAST:event_btn_Cancel5ActionPerformed

    
    public void UpdateTableVehicle(){
        try{
            conn = DBconnection.jdbcConnect();
            String Vehicle = "Select v_id as 'ID', plateNo as 'Plate No.', model as 'Model', type as 'Type', capacity as 'Capacity', vehicle_status as 'Status' from tbl_Vehicle";
            pst = conn.prepareStatement(Vehicle);
            rs=pst.executeQuery();
            tbl_Vehicle.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public void UpdateTableEmployee(){
        try{
            conn = DBconnection.jdbcConnect();
            String Vehicle = "Select emp_id as 'ID', emp_fname as 'Firstname', emp_lname as 'Lastname', emp_mi as 'M.I', user_level as 'User level', username as 'username' from tbl_employee";
            pst = conn.prepareStatement(Vehicle);
            rs=pst.executeQuery();
            tbl_employee.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
        public void UpdateTableService(){
        try{
            conn = DBconnection.jdbcConnect();
            String Vehicle = "Select svc_id as 'ID' , Service_Type as 'Service Type'  from tbl_service";
            pst = conn.prepareStatement(Vehicle);
            rs=pst.executeQuery();
            tbl_Service.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
        
        public void UpdateTableRentalRate(){
        try{
            conn = DBconnection.jdbcConnect();
            String Vehicle = "Select rent_id as 'ID', Rental_Type as 'Type', Rental_Daily as 'Daily', Rental_Weekly as 'Weekly', Rental_Monthly as 'Monthly'  from tbl_RentalRate";
            pst = conn.prepareStatement(Vehicle);
            rs=pst.executeQuery();
            tbl_RentalRate.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }          
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog AddVehicle;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel Background_Location;
    private javax.swing.JLabel Background_Rate;
    private javax.swing.JLabel Background_Service;
    private javax.swing.JDialog EditVehicle;
    private javax.swing.JLabel Rental_Background;
    private javax.swing.JLabel Userlevel_Background;
    private javax.swing.JLabel Vehicle_Background;
    private javax.swing.JMenuItem add;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Add1;
    private javax.swing.JButton btn_Add2;
    private javax.swing.JButton btn_Add3;
    private javax.swing.JButton btn_Cancel1;
    private javax.swing.JButton btn_Cancel2;
    private javax.swing.JButton btn_Cancel3;
    private javax.swing.JButton btn_Cancel4;
    private javax.swing.JButton btn_Cancel5;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Delete1;
    private javax.swing.JButton btn_Delete2;
    private javax.swing.JButton btn_Delete3;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Edit1;
    private javax.swing.JButton btn_Edit2;
    private javax.swing.JButton btn_Edit3;
    private javax.swing.JButton btn_Save1;
    private javax.swing.JButton btn_Save2;
    public javax.swing.JButton btn_Save3;
    private javax.swing.JButton btn_Save4;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_Upload;
    private javax.swing.JButton btn_Upload1;
    private javax.swing.JComboBox cbo_userlevel;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Location;
    private javax.swing.JPanel jPanel_Rate;
    private javax.swing.JPanel jPanel_Service;
    private javax.swing.JPanel jPanel_Userlevel;
    private javax.swing.JPanel jPanel_userlevel;
    private javax.swing.JPanel jPanel_vehicle;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JLabel lbl_svcid;
    public javax.swing.JLabel lbl_vid;
    public javax.swing.JLabel lbl_vid1;
    public javax.swing.JSpinner spin_Capacity;
    public javax.swing.JSpinner spin_Capacity1;
    private javax.swing.JTable tbl_RentalRate;
    private javax.swing.JTable tbl_Service;
    private javax.swing.JTable tbl_Vehicle;
    private javax.swing.JTable tbl_employee;
    private javax.swing.JTextField txt_Daily;
    public javax.swing.JTextField txt_Model;
    public javax.swing.JTextField txt_Model1;
    private javax.swing.JTextField txt_Monthly;
    public javax.swing.JTextField txt_PlateNo;
    public javax.swing.JTextField txt_PlateNo1;
    private javax.swing.JTextField txt_RentID;
    public javax.swing.JTextField txt_Type;
    public javax.swing.JTextField txt_Type1;
    private javax.swing.JTextField txt_VehicleType;
    private javax.swing.JTextField txt_Weekly;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mi;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search1;
    private javax.swing.JTextField txt_service;
    private javax.swing.JTextField txt_service1;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
